config/routes.rb
Rails.application.routes.draw do
  resources :watches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/watch.rb
class Watch < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
  before_action :set_watch, only: [:show, :edit, :update, :destroy]

  # GET /watches
  # GET /watches.json
  def index
    @watches = Watch.order(id: :desc).all
  end

  # GET /watches/1
  # GET /watches/1.json
  def show
  end

  # GET /watches/new
  def new
    @watch = Watch.new
  end

  # GET /watches/1/edit
  def edit
  end

  # POST /watches
  # POST /watches.json
  def create
    @watch = Watch.new(watch_params)

    respond_to do |format|
      if @watch.save
        format.html { redirect_to @watch, notice: 'Watch was successfully created.' }
        format.json { render :show, status: :created, location: @watch }
      else
        format.html { render :new }
        format.json { render json: @watch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /watches/1
  # PATCH/PUT /watches/1.json
  def update
    respond_to do |format|
      if @watch.update(watch_params)
        format.html { redirect_to @watch, notice: 'Watch was successfully updated.' }
        format.json { render :show, status: :ok, location: @watch }
      else
        format.html { render :edit }
        format.json { render json: @watch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /watches/1
  # DELETE /watches/1.json
  def destroy
    @watch.destroy
    respond_to do |format|
      format.html { redirect_to watches_url, notice: 'Watch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_watch
      @watch = Watch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def watch_params
      params.require(:watch).permit(:temp, :human)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/watches/_form.html.erb
<%= form_with(model: watch, local: true) do |form| %>
  <% if watch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(watch.errors.count, "error") %> prohibited this watch from being saved:</h2>

      <ul>
        <% watch.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :temp %>
    <%= form.text_field :temp %>
  </div>

  <div class="field">
    <%= form.label :human %>
    <%= form.text_field :human %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/watches/edit.html.erb
<h1>Editing Watch</h1>

<%= render 'form', watch: @watch %>

<%= link_to 'Show', @watch %> |
<%= link_to 'Back', watches_path %>

app/views/watches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Watches</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Temp</th>
      <th>Human</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @watches.each do |watch| %>
      <tr>
        <td><%= l watch.created_at %></td>
        <td><%= watch.temp %></td>
        <td><%= watch.human %></td>
        <td><%= link_to 'Show', watch %></td>
        <td><%= link_to 'Edit', edit_watch_path(watch) %></td>
        <td><%= link_to 'Destroy', watch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Watch', new_watch_path %>

app/views/watches/new.html.erb
<h1>New Watch</h1>

<%= render 'form', watch: @watch %>

<%= link_to 'Back', watches_path %>

app/views/watches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Temp:</strong>
  <%= @watch.temp %>
</p>

<p>
  <strong>Human:</strong>
  <%= @watch.human %>
</p>

<%= link_to 'Edit', edit_watch_path(@watch) %> |
<%= link_to 'Back', watches_path %>